server:
    port: 8080
    
spring:
    application:
        name: springboot-redis
    redis:
        timeout: 6000ms
        password: 
        cluster:
            max-redirects: 3            # 获取失败 最大重定向次数  
            nodes:                      # 单机配置：host/port
                - 192.168.0.103:6010
                - 192.168.0.103:6020
                - 192.168.0.103:6030
                - 192.168.0.103:6040
                - 192.168.0.103:6050
                - 192.168.0.103:6060
        lettuce:                        # jedis/lettuce
            pool:
                max-active: 1000        # 连接池最大的连接数，若使用负值表示没有限制
                max-idle: 100           # 最大空闲连接数
                min-idle: 10            # 最小空闲连接数
                max-wait: 10s           # 连接池最大阻塞等待时间